throttle_scans: 1
map_frame     : "map"
base_frame    : "base_link" 
odom_frame    : "odom"

map_update_interval : 5.0 #2.0 
maxUrange           : 6.0
maxRange            : 8.0
sigma               : 0.05
kernelSize          : 1
lstep               : 0.05
astep               : 0.05
iterations          : 5
lsigma              : 0.075
ogain               : 3.0
lskip               : 0
minimumScore        : 200.0
lobsGain            : 3

srr : 0.1
srt : 0.2
str : 0.1
stt : 0.2

linearUpdate    : 0.05 #0.25 #0.5
angularUpdate   : 0.05 #0.25 #0.5
temporalUpdate  : 0.1 #0.5 #-1.0

resampleThreshold : 0.5
particles         : 100

xmin  : -15 #-10.0
ymin  : -15 #-10.0
xmax  : 15 #10.0
ymax  : 15 #10.0
delta : 0.01

llsamplerange : 0.01
llsamplestep  : 0.01
lasamplerange : 0.005
lasamplestep  : 0.005

transform_publish_period  : 0.2
occ_thresh                : 0.25
